### ISSUE TITLE
get_token problem

### ISSUE THREAD

**Issue by Struggle-YD** [soodoku/clarifai#2]
dear team
hi, when i use the function get_token ,i meet the follows error

Error in Sys.setenv(ClarifaiToken = token_info$access_token) : 
  wrong length for argument

thank you!

**Comment by soodoku** [comment]
Right --- I don't think your secret_id() is succeeding. I will aim to produce a more helpful error message. Thanks for bringing it to my attention.

**Comment by soodoku** [comment]
After secret_id, check: 

```
Sys.getenv('ClarifaiId')
Sys.getenv('ClarifaiSecret')
```

If these are coming out as empty strings that is a problem. Let me know and I will check if there are any other issues. I don't think so but maybe.
