### ISSUE TITLE
Add v2 Support

### ISSUE THREAD

**Issue by eddiezane** [soodoku/clarifai#6]
Hey @soodoku - thanks for this awesome community contribution!

My name is Eddie and I serve our developer community @clarifai.

We've had some requests from customers for this library to support v2 of our API and  [API Keys](http://blog.clarifai.com/introducing-api-keys-a-safer-way-to-authenticate-your-applications/).

v1 of our API is most likely going to be deprecated by the end of this year and API Keys do not work with the `/v1/token` endpoint/session tokens.

All newly created apps only have access to v2 and API keys so folks are running into an issue when trying to use your rad library.

We're happy to aide in the work for this but wanted to check with you first whether or not you'd merge that PR.

Not that familiar with the R ecosystem but it seems that we'd be unable to strip v1 support without screwing existing users over.

What are your thoughts?

**Comment by soodoku** [comment]
Dear @eddiezane ,

Many apologies for the delay in responding. I was away.

Re. the contribution: You are very welcome! I am a huge supporter of Clarifai. 

I completely understand the demand for revamped 2.0 API, which is fantastic. I am very happy to merge the PR. I am also happy to transfer ownership of the repo. to clarifai. 

p.s. I created this simple application: https://github.com/soodoku/clarifai_gender
and wrote this in 2015: http://gbytes.gsood.com/2015/12/31/clarifaing-the-future-of-clarifai-some-thoughts/

**Comment by eddiezane** [comment]
@soodoku no worries at all - thanks for the reply.

Great to hear. We'll get this into our pipe. Not sure on a timeline at the moment.

Appreciate the offer but I'll hold off on taking ownership for the time being as we have no R experts in house.

--

That's a great app you built. Have you seen our [Demographics Model](https://clarifai.com/models/demographics-image-recognition-model/c0c0ac362b03416da06ab3fa36fb58e3)?

**Comment by soodoku** [comment]
aah --- let's coordinate on efforts on supporting v2 then. loop me into group discussion. happy to create tasks, assign tasks, add people to the repo. so you can directly contribute, etc.
 
re. demographics model --- ya, i know. it works pretty well. problem is that there is no one model for photos taken from all distances, for all countries etc. so imp. for clarifai to utilize as much metadata it can get from the user as possible. but more on that offline.

**Comment by SeverinJB** [comment]
Hi @soodoku,

do you have any plans to upgrade your package?
I am a Digital Humanist and used your package already once in order to analyse art. I would love to use it further. 

Thanks for your response!
Severin

**Comment by Ranemone** [comment]
Hello,
Thanks for this package
Any update on the handeling of v2 version?
V1 is now deprecated and the package is unusable

Regards

**Comment by soodoku** [comment]
working on the v2. will release the first draft within a week.

**Comment by Ranemone** [comment]
Ok, great!
Thanks for the answer @soodoku :)

**Comment by Ranemone** [comment]
Hello @soodoku ,
Happy new year! Best wishes
Any update on the release?
Kind regards

**Comment by Vasilim** [comment]
Looking forward to v2 support!

**Comment by ele6** [comment]
Looking forward to v2 support!
Error in Sys.setenv(ClarifaiToken = token_info$access_token) : 
  wrong length for argument

**Comment by sjgknight** [comment]
Hey thanks for the package! Wondering if it has been updated for v2 now? Was hoping to use it but getting an error at get_token stage. Cheers
